//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudTemplate.Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MudTemplate.Shared.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BadRequestException {
            get {
                return ResourceManager.GetString("BadRequestException", resourceCulture);
            }
        }
        
        public static string ConflicException {
            get {
                return ResourceManager.GetString("ConflicException", resourceCulture);
            }
        }
        
        public static string FileRemoveFailed {
            get {
                return ResourceManager.GetString("FileRemoveFailed", resourceCulture);
            }
        }
        
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        public static string ForbiddenException {
            get {
                return ResourceManager.GetString("ForbiddenException", resourceCulture);
            }
        }
        
        public static string ResourceValidationException {
            get {
                return ResourceManager.GetString("ResourceValidationException", resourceCulture);
            }
        }
        
        public static string RestException {
            get {
                return ResourceManager.GetString("RestException", resourceCulture);
            }
        }
        
        public static string ToDoItemCouldNotBeFound {
            get {
                return ResourceManager.GetString("ToDoItemCouldNotBeFound", resourceCulture);
            }
        }
        
        public static string UnauthorizedException {
            get {
                return ResourceManager.GetString("UnauthorizedException", resourceCulture);
            }
        }
        
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        public static string UserImageCouldNotBeFound {
            get {
                return ResourceManager.GetString("UserImageCouldNotBeFound", resourceCulture);
            }
        }
        
        public static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        public static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        public static string RecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("RecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        public static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        public static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        public static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        public static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
        
        public static string PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        public static string WaitForConfirmationEmailResendDelay {
            get {
                return ResourceManager.GetString("WaitForConfirmationEmailResendDelay", resourceCulture);
            }
        }
        
        public static string WaitForResetPasswordEmailResendDelay {
            get {
                return ResourceManager.GetString("WaitForResetPasswordEmailResendDelay", resourceCulture);
            }
        }
        
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        public static string UpdateConcurrencyException {
            get {
                return ResourceManager.GetString("UpdateConcurrencyException", resourceCulture);
            }
        }
        
        public static string KnownException {
            get {
                return ResourceManager.GetString("KnownException", resourceCulture);
            }
        }
        
        public static string ResourceNotFoundException {
            get {
                return ResourceManager.GetString("ResourceNotFoundException", resourceCulture);
            }
        }
        
        public static string TooManyRequestsExceptions {
            get {
                return ResourceManager.GetString("TooManyRequestsExceptions", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        public static string AlreadyHaveAccountMessage {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountMessage", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string CheckSpamMailMessage {
            get {
                return ResourceManager.GetString("CheckSpamMailMessage", resourceCulture);
            }
        }
        
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        public static string ConfirmEmailTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailTitle", resourceCulture);
            }
        }
        
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string DontHaveAccountMessage {
            get {
                return ResourceManager.GetString("DontHaveAccountMessage", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string EmailConfirmationFailedMessage {
            get {
                return ResourceManager.GetString("EmailConfirmationFailedMessage", resourceCulture);
            }
        }
        
        public static string EmailConfirmationTitle {
            get {
                return ResourceManager.GetString("EmailConfirmationTitle", resourceCulture);
            }
        }
        
        public static string EmailConfirmedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfullyMessage", resourceCulture);
            }
        }
        
        public static string ForgetPasswordMessage {
            get {
                return ResourceManager.GetString("ForgetPasswordMessage", resourceCulture);
            }
        }
        
        public static string ForgetPasswordTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordTitle", resourceCulture);
            }
        }
        
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        public static string GenderCustom {
            get {
                return ResourceManager.GetString("GenderCustom", resourceCulture);
            }
        }
        
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        public static string GitHubRepo {
            get {
                return ResourceManager.GetString("GitHubRepo", resourceCulture);
            }
        }
        
        public static string InvalidConfirmationLinkMessage {
            get {
                return ResourceManager.GetString("InvalidConfirmationLinkMessage", resourceCulture);
            }
        }
        
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        public static string NoTodos {
            get {
                return ResourceManager.GetString("NoTodos", resourceCulture);
            }
        }
        
        public static string NotReceivedConfirmationEmailMessage {
            get {
                return ResourceManager.GetString("NotReceivedConfirmationEmailMessage", resourceCulture);
            }
        }
        
        public static string NotReceivedConfirmationEmailMessage1 {
            get {
                return ResourceManager.GetString("NotReceivedConfirmationEmailMessage1", resourceCulture);
            }
        }
        
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string PasswordChangedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfullyMessage", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyAgreementMessage {
            get {
                return ResourceManager.GetString("PrivacyPolicyAgreementMessage", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyPageMessage {
            get {
                return ResourceManager.GetString("PrivacyPolicyPageMessage", resourceCulture);
            }
        }
        
        public static string PrivacyPolicySectionMessage {
            get {
                return ResourceManager.GetString("PrivacyPolicySectionMessage", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        public static string ProfileUpdatedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfullyMessage", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string ResendConfirmationLinkMessage {
            get {
                return ResourceManager.GetString("ResendConfirmationLinkMessage", resourceCulture);
            }
        }
        
        public static string ResendEmail {
            get {
                return ResourceManager.GetString("ResendEmail", resourceCulture);
            }
        }
        
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        public static string ResetPasswordLinkSentMessage {
            get {
                return ResourceManager.GetString("ResetPasswordLinkSentMessage", resourceCulture);
            }
        }
        
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string SelectBirthDate {
            get {
                return ResourceManager.GetString("SelectBirthDate", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        public static string SingUpTitle {
            get {
                return ResourceManager.GetString("SingUpTitle", resourceCulture);
            }
        }
        
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string TodoAddPlaceholder {
            get {
                return ResourceManager.GetString("TodoAddPlaceholder", resourceCulture);
            }
        }
        
        public static string TodoSearchPlaceholder {
            get {
                return ResourceManager.GetString("TodoSearchPlaceholder", resourceCulture);
            }
        }
        
        public static string HomeMessage {
            get {
                return ResourceManager.GetString("HomeMessage", resourceCulture);
            }
        }
        
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        public static string TodoTitle {
            get {
                return ResourceManager.GetString("TodoTitle", resourceCulture);
            }
        }
        
        public static string UploadNewProfileImage {
            get {
                return ResourceManager.GetString("UploadNewProfileImage", resourceCulture);
            }
        }
        
        public static string ArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        public static string AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties {
            get {
                return ResourceManager.GetString("AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties", resourceCulture);
            }
        }
        
        public static string AttributeStore_Unknown_Property {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Property", resourceCulture);
            }
        }
        
        public static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        public static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        public static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        public static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        public static string CustomValidationAttribute_Method_Must_Return_ValidationResult {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Must_Return_ValidationResult", resourceCulture);
            }
        }
        
        public static string CustomValidationAttribute_Method_Not_Found {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Not_Found", resourceCulture);
            }
        }
        
        public static string CustomValidationAttribute_Method_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Required", resourceCulture);
            }
        }
        
        public static string CustomValidationAttribute_Method_Signature {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Signature", resourceCulture);
            }
        }
        
        public static string CustomValidationAttribute_Type_Conversion_Failed {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Conversion_Failed", resourceCulture);
            }
        }
        
        public static string CustomValidationAttribute_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        public static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string CustomValidationAttribute_ValidatorType_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidatorType_Required", resourceCulture);
            }
        }
        
        public static string DataTypeAttribute_EmptyDataTypeString {
            get {
                return ResourceManager.GetString("DataTypeAttribute_EmptyDataTypeString", resourceCulture);
            }
        }
        
        public static string DisplayAttribute_PropertyNotSet {
            get {
                return ResourceManager.GetString("DisplayAttribute_PropertyNotSet", resourceCulture);
            }
        }
        
        public static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        public static string EnumDataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        public static string EnumDataTypeAttribute_TypeNeedsToBeAnEnum {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeNeedsToBeAnEnum", resourceCulture);
            }
        }
        
        public static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        public static string LengthAttribute_InvalidValueType {
            get {
                return ResourceManager.GetString("LengthAttribute_InvalidValueType", resourceCulture);
            }
        }
        
        public static string LocalizableString_LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizableString_LocalizationFailed", resourceCulture);
            }
        }
        
        public static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        public static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string MetadataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("MetadataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        public static string MinLengthAttribute_InvalidMinLength {
            get {
                return ResourceManager.GetString("MinLengthAttribute_InvalidMinLength", resourceCulture);
            }
        }
        
        public static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        public static string RangeAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("RangeAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        public static string RangeAttribute_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("RangeAttribute_MinGreaterThanMax", resourceCulture);
            }
        }
        
        public static string RangeAttribute_Must_Set_Min_And_Max {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Min_And_Max", resourceCulture);
            }
        }
        
        public static string RangeAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string RegularExpressionAttribute_Empty_Pattern {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_Empty_Pattern", resourceCulture);
            }
        }
        
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string StringLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        public static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        public static string UIHintImplementation_ControlParameterKeyIsNotAString {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNotAString", resourceCulture);
            }
        }
        
        public static string UIHintImplementation_ControlParameterKeyIsNull {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNull", resourceCulture);
            }
        }
        
        public static string UIHintImplementation_ControlParameterKeyOccursMoreThanOnce {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyOccursMoreThanOnce", resourceCulture);
            }
        }
        
        public static string UIHintImplementation_NeedEvenNumberOfControlParameters {
            get {
                return ResourceManager.GetString("UIHintImplementation_NeedEvenNumberOfControlParameters", resourceCulture);
            }
        }
        
        public static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
        
        public static string ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource {
            get {
                return ResourceManager.GetString("ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource", resourceCulture);
            }
        }
        
        public static string ValidationAttribute_IsValid_NotImplemented {
            get {
                return ResourceManager.GetString("ValidationAttribute_IsValid_NotImplemented", resourceCulture);
            }
        }
        
        public static string ValidationAttribute_NeedBothResourceTypeAndResourceName {
            get {
                return ResourceManager.GetString("ValidationAttribute_NeedBothResourceTypeAndResourceName", resourceCulture);
            }
        }
        
        public static string ValidationAttribute_ResourcePropertyNotStringType {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourcePropertyNotStringType", resourceCulture);
            }
        }
        
        public static string ValidationAttribute_ResourceTypeDoesNotHaveProperty {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourceTypeDoesNotHaveProperty", resourceCulture);
            }
        }
        
        public static string ValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string Validator_InstanceMustMatchValidationContextInstance {
            get {
                return ResourceManager.GetString("Validator_InstanceMustMatchValidationContextInstance", resourceCulture);
            }
        }
        
        public static string Validator_Property_Value_Wrong_Type {
            get {
                return ResourceManager.GetString("Validator_Property_Value_Wrong_Type", resourceCulture);
            }
        }
        
        public static string IsAcceptPrivacy {
            get {
                return ResourceManager.GetString("IsAcceptPrivacy", resourceCulture);
            }
        }
        
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string YouHaveToAcceptPrivacyPolicy {
            get {
                return ResourceManager.GetString("YouHaveToAcceptPrivacyPolicy", resourceCulture);
            }
        }
        
        public static string GoToToday {
            get {
                return ResourceManager.GetString("GoToToday", resourceCulture);
            }
        }
        
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        public static string SignOutPrompt {
            get {
                return ResourceManager.GetString("SignOutPrompt", resourceCulture);
            }
        }
        
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
    }
}
